In [83]:
import cv2

In [84]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [85]:
import numpy as np

In [86]:
a=np.arange(0,40)

In [87]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [90]:
a=a.reshape(8,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [89]:
i=0
while i<a.shape[1]:
    print(a[:,i])
    i+=2

[ 0  5 10 15 20 25 30 35]
[ 2  7 12 17 22 27 32 37]
[ 4  9 14 19 24 29 34 39]


In [161]:
i=0
b=np.empty(0,dtype=int)
while i<a.shape[1]:
    b=np.hstack((b,a[:,i]))
    i+=2
b=b.reshape(int((a.shape[1]+1)/2),a.shape[0])

In [163]:
i=0
c=np.array([],dtype=int)
while i<b.shape[1]:
    c=np.hstack((c,b[:,i]))
    i+=3
c=c.reshape(b.shape[0],int((b.shape[1]+1)/3))
c

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [27]:
def nth(arr, n):
    if(n>len(arr) or n<1):
        print("There is no largest element with rank",n)
        return
    g=arr[0]
    b=g
    low=arr[0]
    for i in arr:
        if b<i:
            b=i
        if low>i:
            low=i
    if n==1:
        print(b)
    else:
        while n!=1:
            g=low
            for i in arr:
                if g<i and i<b:
                    g=i
            n-=1
            b=g
        print(g)

In [28]:
arr=np.asarray([12,34,40,7,1,0])
nth(arr,5)

1


In [40]:
arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[7770, 2973, 4247, 7038, 9697],
       [ 546, 7326, 6277, 9943, 2505]])

In [45]:
def normalise(arr):
    high=arr.flatten()[0]
    low=high
    new=np.array([])
    for i in arr.flatten():
        if high<i:
            high=i
        if low>i:
            low=i
    step=high-low
    for i in arr.flatten():
        new=np.append(new,(i-low)/step)
    new=new.reshape(arr.shape)
    return new

In [46]:
normalise(arr2)

array([[ 0.76875599,  0.25827392,  0.3938491 ,  0.69085878,  0.97382143],
       [ 0.        ,  0.72150686,  0.60987549,  1.        ,  0.20847079]])

In [75]:
a_missing=np.array([1,2,3,4,4,5,np.nan])
a_missing

array([  1.,   2.,   3.,   4.,   4.,   5.,  nan])

In [78]:
def check_missing(a_missing):
    flag=np.isnan(a_missing).any()
    if flag:
        print("Array has missing values")
    else:
        print("Array has no missing values")

In [81]:
check_missing(a_missing)

Array has missing values
