Q1. **Get the positions where elements of a and b match**

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Output:

(array([1, 3, 5, 7]),)



In [4]:
# Write code for Q1 here
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

Q2. **Get all items between 5 and 10 from a.**

a = np.array([2, 6, 1, 9, 10, 3, 27])

In [5]:
# Write code for Q2 here
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5)&(a<10)]

array([6, 9])

Q3. **Swap columns 1 and 2 in the array arr.**

arr = np.arange(9).reshape(3,3)

In [11]:
# Write code for Q3 here
arr = np.arange(9).reshape(3,3)
t=np.copy(arr[:,0])
arr[:,0]=arr[:,1]
arr[:,1]=t
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q4. Reverse the rows of a 2D array arr.

arr = np.arange(9).reshape(3,3)

In [12]:
# Write code for Q4 here
arr = np.arange(9).reshape(3,3)
i=list(range(len(arr)-1,-1,-1))
arr=arr[i]
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q5. Find the 5th and 95th percentile of iris's sepallength
Note - Find input code in the next cell

In [24]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

# Write code for Q5 here
print("5th percentile=",np.percentile(sepallength,5))
print("95th percentile=",np.percentile(sepallength,95))

5th percentile= 4.6
95th percentile= 7.255


Q6. Find the positions of NaN in the sepalLength numpy array

In [68]:
# This is the input of your question
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

sepalLength=iris_2d[:,0]
# This is the sepalLength
print(sepalLength)

# Write your code here
np.where(np.isnan(sepalLength))
# Hint - You can use the isNan() function.

[ 5.1  4.9  4.7  4.6  5.   5.4  4.6  5.   4.4  4.9  5.4  4.8  4.8  4.3  5.8
  5.7  5.4  5.1  5.7  5.1  5.4  nan  4.6  5.1  nan  5.   5.   5.2  5.2  4.7
  4.8  5.4  5.2  5.5  4.9  5.   5.5  4.9  4.4  5.1  5.   4.5  4.4  5.   5.1
  4.8  5.1  4.6  5.3  5.   7.   6.4  6.9  5.5  6.5  5.7  6.3  4.9  6.6  5.2
  5.   5.9  nan  6.1  5.6  6.7  5.6  5.8  6.2  5.6  5.9  6.1  6.3  6.1  6.4
  6.6  6.8  6.7  6.   5.7  5.5  5.5  5.8  6.   5.4  6.   6.7  6.3  5.6  5.5
  5.5  6.1  5.8  5.   5.6  5.7  5.7  6.2  5.1  5.7  6.3  5.8  7.1  nan  6.5
  7.6  4.9  7.3  6.7  7.2  6.5  6.4  6.8  5.7  5.8  6.4  6.5  7.7  7.7  6.
  6.9  5.6  7.7  6.3  6.7  7.2  6.2  6.1  6.4  7.2  7.4  7.9  6.4  6.3  6.1
  7.7  6.3  6.4  6.   6.9  6.7  6.9  5.8  6.8  6.7  6.7  6.3  6.5  6.2  5.9]


(array([ 21,  24,  62, 103]),)

Q7 .Replace all the null values with 0 in the above used sepalLength array

In [69]:
# Write your code here
sepalLength[np.isnan(sepalLength)]=0
print(sepalLength)

[ 5.1  4.9  4.7  4.6  5.   5.4  4.6  5.   4.4  4.9  5.4  4.8  4.8  4.3  5.8
  5.7  5.4  5.1  5.7  5.1  5.4  0.   4.6  5.1  0.   5.   5.   5.2  5.2  4.7
  4.8  5.4  5.2  5.5  4.9  5.   5.5  4.9  4.4  5.1  5.   4.5  4.4  5.   5.1
  4.8  5.1  4.6  5.3  5.   7.   6.4  6.9  5.5  6.5  5.7  6.3  4.9  6.6  5.2
  5.   5.9  0.   6.1  5.6  6.7  5.6  5.8  6.2  5.6  5.9  6.1  6.3  6.1  6.4
  6.6  6.8  6.7  6.   5.7  5.5  5.5  5.8  6.   5.4  6.   6.7  6.3  5.6  5.5
  5.5  6.1  5.8  5.   5.6  5.7  5.7  6.2  5.1  5.7  6.3  5.8  7.1  0.   6.5
  7.6  4.9  7.3  6.7  7.2  6.5  6.4  6.8  5.7  5.8  6.4  6.5  7.7  7.7  6.
  6.9  5.6  7.7  6.3  6.7  7.2  6.2  6.1  6.4  7.2  7.4  7.9  6.4  6.3  6.1
  7.7  6.3  6.4  6.   6.9  6.7  6.9  5.8  6.8  6.7  6.7  6.3  6.5  6.2  5.9]


Q8. Find the 2nd largest value for the given array.

In [58]:
# Input
arr=np.random.randint(23,78, size=9).reshape(3,3)
print(arr)
    
# Write your code here
np.sort(np.ravel(arr))[7]

[[28 76 41]
 [55 49 76]
 [60 25 72]]


76

Q9. From the array a, replace all values greater than 30 by 30 and less than 10 by 10.

In [63]:
# Input
arr=np.random.randint(1,78, size=9).reshape(3,3)
print(arr)

# Write your code here
arr[np.where(arr>30)]=30
arr[np.where(arr<10)]=10
print(arr)

[[39 40 36]
 [44 32 38]
 [25 25 19]]
[[30 30 30]
 [30 30 30]
 [25 25 19]]


Q10. Drop all nan values from a 1D numpy array

In [77]:
arr=np.array([1,2,3,np.nan,5,6,7,np.nan])
print(arr)

# Write code here
arr=np.delete(arr,np.where(np.isnan(arr)))
print(arr)

[  1.   2.   3.  nan   5.   6.   7.  nan]
[ 1.  2.  3.  5.  6.  7.]
