In [1]:
import numpy as np

In [2]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

In [4]:
t=np.copy(arr1[:,0])
arr1[:,0]=arr1[:,3]
arr1[:,3]=t
arr1

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [5]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

In [6]:
i=list(range(len(arr1)-1,-1,-1))
arr1=arr1[i]
arr1

array([[18, 16, 17, 15, 19],
       [13, 11, 12, 10, 14],
       [ 8,  6,  7,  5,  9],
       [ 3,  1,  2,  0,  4]])

In [7]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[  1.,   2.,  nan],
       [  4.,   5.,   6.],
       [ nan,  nan,   9.]])

In [8]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [9]:
mean=np.nanmean(arr2)
i=np.where(np.isnan(arr2))
arr2[i]=mean
arr2

array([[ 1. ,  2. ,  4.5],
       [ 4. ,  5. ,  6. ],
       [ 4.5,  4.5,  9. ]])

In [10]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[11, 60, 45, 50],
       [78, 60, 37, 95],
       [14, 32, 55, 83],
       [ 5,  9, 74, 59],
       [78, 35, 69, 89]])

In [11]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [12]:
i=np.where((arr3>25) | (arr3%3==0))
arr3[i]

array([60, 45, 50, 78, 60, 37, 95, 32, 55, 83,  9, 74, 59, 78, 35, 69, 89])

In [13]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [14]:
print("10th percentile of arr3=",np.percentile(arr3,10))
print("25th percentile of arr3=",np.percentile(arr3,25))
print("50th percentile of arr3=",np.percentile(arr3,50))

10th percentile of arr3= 10.8
25th percentile of arr3= 34.25
50th percentile of arr3= 57.0
