In [4]:
import numpy as np

In [5]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [6]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [7]:
i=list(range(0,arr1.shape[1],2))
arr1[:,i]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [8]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [10]:
i=list(range(0,arr1.shape[0],3))
j=list(range(0,arr1.shape[1],2))
arr1[i][:,j]

array([ 0, 17, 34])

In [7]:
# Setup for question
  
# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[2790, 8908, 1652, 2889, 1474],
       [1579, 7303, 4010,  876, 6499]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
def normalise(arr):
    high=arr.flatten()[0]
    low=high
    new=np.array([])
    for i in arr.flatten(): #finding the highest and the lowest values in the array
        if high<i:
            high=i
        if low>i:
            low=i
    step=high-low
    for i in arr.flatten():
        new=np.append(new,(i-low)/step)
    new=new.reshape(arr.shape)  #getting it back to the previous shape
    return new

In [10]:
normalise(arr2)

array([[0.23829681, 1.        , 0.09661355, 0.25062251, 0.07445219],
       [0.0875249 , 0.8001743 , 0.39018924, 0.        , 0.7000747 ]])

In [11]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [0]:
def check_missing(a_missing):
    flag=np.isnan(a_missing).any()
    if flag:
        print("Array has missing values")
    else:
        print("Array has no missing values")

In [14]:
a_missing=np.array([1,2,3,4,4,5,np.nan])
a_missing

array([ 1.,  2.,  3.,  4.,  4.,  5., nan])

In [15]:
check_missing(a_missing)

Array has missing values


In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
def nth(arr, n):
    if(n>len(arr) or n<1):
        print("There is no largest element with rank",n)
        return
    g=arr[0]  #variable for greatest element of the required rank
    b=g
    low=arr[0]
    for i in arr:
        if b<i:
            b=i
        if low>i:
            low=i
    if n==1:
        print(b)
    else:
        while n!=1:
            g=low
            for i in arr:
                if g<i and i<b:
                    g=i
            n-=1
            b=g
        print(g)

In [18]:
arr=np.array([12,34,40,7,1,0])
nth(arr,3)
nth(arr,1)
nth(arr,15)
nth(arr,-4)

12
40
There is no largest element with rank 15
There is no largest element with rank -4
